name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 188.245.155.234 >> ~/.ssh/known_hosts

      - name: Deploy Application
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa root@188.245.155.234 << 'EOF'
          eval `ssh-agent -s`
          ssh-add ~/.ssh/id_rsa
          cd Order-Receipt-Generator  # Change this to your actual app path
          git pull origin main
          npm install --production
          pm2 restart Order-reciept-Generator
          pm2 save
          EOF
